import { db } from "@/core/db/client";
import { getAllTools } from "@/core/ai/tool-registry";
import { ensureDefaultRoutes, resolveRoute } from "@/core/ai/routing";
import type { ChatMessage } from "@/core/ai/provider";
import { modules } from "@/modules/registry";

export const maxDuration = 300;

async function systemPrompt() {
  const { renderMemoryContext } = await import("@/core/memory");
  const moduleList = modules.map((m) => m.id).join(", ");
  return [
    "You are the AI core of apOS — the user's Agentic Personalized Operating System.",
    `Installed modules: ${moduleList}.`,
    "Use the available tools to read and change the user's data when asked.",
    "Only call a mutating tool (create, update, delete, send, notify) when the user explicitly asks to change something. For a question, answer from read-only tools — never create, modify, or send anything as a side effect.",
    "To show a chart or graph, you MUST call the viz.chart tool with the real numbers, then paste its returned `embed` markdown VERBATIM into your reply — use the EXACT /api/charts/<id> url it returns. NEVER invent a filename, path or link, and NEVER print chart data as JSON, a code block, or ASCII.",
    "Ground everything in tool results — every number, ticker and chart data point must come from a tool you called in this conversation. NEVER invent figures or placeholder labels (e.g. 'Stock A', a made-up 'vs market' comparison).",
    "For an analysis or report request, be THOROUGH and STRUCTURED: use markdown headings (e.g. ## Summary, ## Performance, ## Positions, ## Observations), lead with the key numbers, and include the relevant chart(s). For a simple question, answer in a few sentences.",
    `Current date-time: ${new Date().toISOString()}`,
    "",
    await renderMemoryContext(),
  ].join("\n");
}

const CHAT_ROUTES = new Set(["chat", "chat.investments"]);

/**
 * What an investments request structurally requires, so we can verify the answer
 * actually delivered it (and retry once if not). Deterministic — no judge LLM.
 */
function analyzeRequest(msg: string): {
  wantsChart: boolean;
  strategyTag: string | null;
} {
  const wantsChart =
    /\b(analy|report|chart|graph|plot|visual|performance|allocation|breakdown|trend)/i.test(
      msg,
    );
  const isStrategy =
    /\b(strateg|tagged?|notes?|marked|generated by|algo|leopold)\b/i.test(msg);
  let strategyTag: string | null = null;
  const quoted = msg.match(/["'“”]([A-Za-z][\w .&-]{0,24})["'“”]/);
  if (quoted) strategyTag = quoted[1].trim();
  else {
    const known = msg.match(/\b(algo|leopold)\b/i);
    if (known) strategyTag = known[1];
  }
  return { wantsChart, strategyTag: isStrategy ? strategyTag : null };
}

export async function POST(req: Request) {
  let body: { messages?: ChatMessage[]; route?: string };
  try {
    body = (await req.json()) as typeof body;
  } catch {
    return Response.json({ error: "invalid JSON body" }, { status: 400 });
  }
  const { messages, route: routeKey } = body;
  if (
    !Array.isArray(messages) ||
    !messages.length ||
    !messages.every(
      (m) =>
        m &&
        (m.role === "user" || m.role === "assistant") &&
        typeof m.content === "string",
    )
  ) {
    return Response.json({ error: "messages required" }, { status: 400 });
  }

  await ensureDefaultRoutes();
  // A surface can ask for a dedicated route (e.g. the Investments page uses a
  // more faithful model); otherwise the default snappy chat.
  const taskKey = routeKey && CHAT_ROUTES.has(routeKey) ? routeKey : "chat";
  const route = await resolveRoute(taskKey);
  // Claude handles the full registry well (and the SDK prompt-caches tool
  // definitions). Small local models get a lean, high-value subset — fewer
  // definitions means less context burned and better tool selection.
  const LEAN_TOOLS = new Set([
    "search.everything",
    "memory.update",
    "memory.remember",
    "memory.recall",
    "tasks.create",
    "tasks.list",
    "tasks.setStatus",
    "notes.create",
    "notes.search",
    "knowledge.capture",
    "knowledge.search",
    "calendar.agenda",
    "ideas.capture",
    "notify.send",
    "viz.chart",
    "market.quote",
    "market.history",
    "market.fairValue",
    "market.healthScore",
  ]);
  // Local models (Ollama, or MLX via LM Studio) get a lean, high-value subset —
  // fewer tool definitions means far less context burned (the full registry is
  // ~10k tokens) and better tool selection. Claude handles the full set.
  // When iSentry is connected, expose the read-only portfolio tools to the lean
  // local-chat subset too — so you can ask about your portfolio on a local model
  // (they gate on config, so they're inert/absent otherwise).
  const { isentryConfigured } = await import("@/modules/investments/db");
  if (isentryConfigured())
    for (const n of [
      "portfolio.summary",
      "portfolio.positions",
      "portfolio.allocation",
      "portfolio.performance",
      "portfolio.transactions",
      "portfolio.byStrategy",
      "portfolio.savings",
    ])
      LEAN_TOOLS.add(n);
  const isLocal = route.providerId === "ollama" || route.providerId === "mlx";
  const tools = isLocal
    ? getAllTools().filter((t) => LEAN_TOOLS.has(t.name))
    : getAllTools();

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      const send = (obj: unknown) =>
        controller.enqueue(encoder.encode(JSON.stringify(obj) + "\n"));
      send({ type: "meta", provider: route.providerId, model: route.model });
      const baseSystem = await systemPrompt();
      // Default chat: reasoning off for snappiness. A dedicated route (e.g.
      // Investments, on the MLX abliterated) lets the provider apply light
      // reasoning so it grounds. Verification runs only on the investments route.
      const reasoning = taskKey === "chat" ? "none" : undefined;
      const verify = taskKey === "chat.investments";
      const want = verify
        ? analyzeRequest(String(messages[messages.length - 1]?.content ?? ""))
        : { wantsChart: false, strategyTag: null };

      // For a strategy analysis, restrict the toolset so the model can only
      // ground in byStrategy (dropping raw transactions / full positions). We
      // also WITHHOLD viz.chart here: given the chart tool, some local models
      // "satisfy" the request by producing only a chart and skip the written
      // report. So the model's one job is the prose; the chart is built
      // deterministically from the byStrategy data below (the backstop).
      const activeTools =
        verify && want.strategyTag
          ? tools.filter((t) =>
              ["portfolio.byStrategy", "portfolio.summary"].includes(t.name),
            )
          : tools;
      const strategyDirective = want.strategyTag
        ? `This is an analysis of ONLY the '${want.strategyTag}' strategy. Call portfolio.byStrategy('${want.strategyTag}') and write a THOROUGH, STRUCTURED written report based strictly on ITS result: use markdown headings (## Summary, ## Per-symbol performance, ## Insights), lead with the key numbers (invested, realized/unrealized P&L, total P&L, return %), and call out the winners, the losers, and any flagged (caveat) symbols. Do NOT analyze raw transactions or the full portfolio. Do NOT draw a chart or emit any chart/tool/JSON syntax — the app attaches the P&L chart automatically. Do not output citation markers like #ref.`
        : undefined;

      // Captured tool results, so the backend can build a chart from them if the
      // model fails to (some local models emit the viz.chart call as TEXT).
      const results: {
        byStrategy?: Record<string, unknown>;
        allocation?: Record<string, unknown>;
      } = {};

      // One model pass. In verify mode we forward progress (tool chips/reasoning)
      // but HOLD the text until it's been checked, so a failed answer can be
      // replaced/completed rather than shown then contradicted.
      const runOnce = async (directive?: string) => {
        const calls = new Set<string>();
        let text = "";
        let err = "";
        try {
          for await (const event of route.provider.run({
            system: directive ? `${baseSystem}\n\n${directive}` : baseSystem,
            messages,
            tools: activeTools,
            toolCtx: { db },
            model: route.model,
            reasoning,
            signal: req.signal,
          })) {
            if (event.type === "tool_call") calls.add(event.name);
            if (event.type === "tool_result") {
              const r = event.result as Record<string, unknown>;
              if (event.name === "portfolio.byStrategy" && r && !r.error) results.byStrategy = r;
              if (event.name === "portfolio.allocation" && r && !r.error) results.allocation = r;
            }
            if (event.type === "text" || event.type === "done") {
              if (event.text) text = event.text;
            } else if (event.type === "error") {
              err = event.message;
            } else if (verify) {
              send(event); // progress only
            }
            if (!verify) send(event);
          }
        } catch (e) {
          err = String(e);
        }
        return { calls, text, err };
      };

      /** Build a chart via the real viz.chart tool from an input; returns embed. */
      const makeChart = async (input: unknown): Promise<string | null> => {
        const viz = getAllTools().find((t) => t.name === "viz.chart");
        if (!viz) return null;
        const r = (await viz.execute(input, { db })) as { embed?: string };
        return r?.embed ?? null;
      };

      try {
        const first = await runOnce(strategyDirective);
        const err = first.err;
        let { calls, text } = first;

        if (verify && !err) {
          // 1) The analysis must be scoped to the strategy — force byStrategy.
          if (
            want.strategyTag &&
            !calls.has("portfolio.byStrategy") &&
            !results.byStrategy
          ) {
            const retry = await runOnce(
              `Your previous attempt was INCOMPLETE. Analyze ONLY the '${want.strategyTag}'-tagged positions: call portfolio.byStrategy('${want.strategyTag}') and base the ENTIRE answer on ITS result — not the full portfolio. Produce the full corrected answer.`,
            );
            if (!retry.err && retry.text) {
              calls = retry.calls;
              text = retry.text;
            }
          }

          // 2) Strip any text-emitted tool-call garbage the model printed.
          const strip = (s: string) =>
            s
              .replace(/<tool_call>[\s\S]*?<\/tool_call>/gi, "")
              .replace(/<function=[\s\S]*?<\/function>/gi, "")
              .replace(/#ref/g, "")
              .trim();
          text = strip(text);

          // 2b) Report completeness: the written analysis is the model's job
          // here (the chart is added below). If it came back near-empty — e.g.
          // it only emitted a chart call, or a one-liner — retry once demanding
          // the full report. Measure prose with any image/chart embeds removed.
          const proseLen = text
            .replace(/!\[[^\]]*\]\([^)]*\)/g, "")
            .replace(/\s+/g, " ")
            .trim().length;
          if (want.strategyTag && proseLen < 120) {
            const retry = await runOnce(
              `Your previous answer was too short. Using portfolio.byStrategy('${want.strategyTag}'), write the FULL structured analysis now: ## Summary (invested, realized/unrealized P&L, return %), ## Per-symbol performance (winners and losers), ## Insights, and note any flagged symbols. Write prose only — do NOT emit any chart or tool syntax; the chart is attached separately.`,
            );
            if (!retry.err && strip(retry.text)) text = strip(retry.text);
          }

          // 3) Deterministic chart backstop: a chart was asked for but none was
          // really produced (the model may text-emit the call) → build it from
          // the data the tools already returned.
          const hasChart = /\/api\/charts\//.test(text);
          if (want.wantsChart && !hasChart) {
            let embed: string | null = null;
            const bs = results.byStrategy?.bySymbol as
              | Array<Record<string, unknown>>
              | undefined;
            if (want.strategyTag && Array.isArray(bs) && bs.length) {
              const data = bs
                .map((s) => ({
                  label: String(s.symbol),
                  value: +(
                    (Number(s.realized_pnl_usd) || 0) +
                    (Number(s.unrealized_pnl_usd) || 0)
                  ).toFixed(2),
                }))
                .filter((d) => Number.isFinite(d.value) && d.value !== 0)
                .sort((a, b) => b.value - a.value);
              if (data.length)
                embed = await makeChart({
                  type: "hbar",
                  title: `${want.strategyTag} — P&L by symbol`,
                  subtitle: "realized + unrealized · USD",
                  unit: "currency",
                  data,
                });
            }
            const slices = results.allocation?.slices as
              | Array<Record<string, unknown>>
              | undefined;
            if (!embed && Array.isArray(slices) && slices.length)
              embed = await makeChart({
                type: "donut",
                title: "Portfolio allocation",
                unit: "currency",
                data: slices,
              });
            if (embed) text = `${text}\n\n${embed}`;
          }

          if (text) send({ type: "text", text });
          send({ type: "done", text });
        }
        if (err) send({ type: "error", message: err });
      } catch (e) {
        send({ type: "error", message: String(e) });
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "application/x-ndjson; charset=utf-8",
      "Cache-Control": "no-cache",
    },
  });
}
